version: '3'

services:
  publisher:
    build: ./publisher
    ports:
      - "3001:3000"
    container_name: express-publisher
    command: npm run start:dev
    volumes:
      - ./webgr-api:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - rabbitmq
  consumer:
    build: ./consumer
    ports:
      - "3000:3000"
    container_name: express-consumer
    command: npm run start:dev
    volumes:
      - ./webgr-api:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:3.9-management-alpine"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "8080:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=rabbit